export default {
    TAB_ROUTES:"TabRoutes",
    MaterialTopTab:'MaterialTopTab',
    ON_BOARDING: 'onBoarding',
    INITIAL_AUTH: "initialAuth",
    LOGIN: "login",
    LogInHomeScreen:'loginHomeScreen',
    SIGNUP: "signup",
    OTP_VERIFICATION: "otpVerification",
    FORGOT_PASSWORD: "forgotPassword",
    HOME:"home",
    FriendStories:'FriendStories',
    Following:'Following',
    Popular:'Popular',
    SEARCH:"Search",
    SearchPeople:'SearchPeople',
    POST:"message",
    NOTIFICATION:"Notification",
    PROFILE:"Profile",
    CATEGORIES:"categories",
    BOOK_SELECTIONS:"bookSelections",
    ANIMATION:"animation",
}
